version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: adaptive_medical_learning
      POSTGRES_USER: medical_user
      POSTGRES_PASSWORD: medical_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: postgres -c shared_preload_libraries=vector

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://medical_user:medical_password@postgres:5432/adaptive_medical_learning
      REDIS_URL: redis://redis:6379/0
      JWT_SECRET_KEY: ${JWT_SECRET_KEY:-your-super-secret-jwt-key-change-in-production}
      JWT_ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      EMBEDDING_MODEL: text-embedding-3-small
      LLM_MODEL: gpt-4o-mini
    depends_on:
      - postgres
      - redis
    volumes:
      - ./app:/app/app
      - ./uploads:/app/uploads
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  celery_worker:
    build: .
    environment:
      DATABASE_URL: postgresql://medical_user:medical_password@postgres:5432/adaptive_medical_learning
      REDIS_URL: redis://redis:6379/0
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      EMBEDDING_MODEL: text-embedding-3-small
      LLM_MODEL: gpt-4o-mini
    depends_on:
      - postgres
      - redis
    volumes:
      - ./app:/app/app
      - ./uploads:/app/uploads
    command: celery -A app.celery_app worker --loglevel=info

volumes:
  postgres_data:
  redis_data:
